name: belatuk_http_server
version: 4.4.0
description: A collection of useful utility classes for building HTTP server.
repository: https://github.com/dart-backend/belatuk_http_server
homepage: https://github.com/dart-backend/belatuk_http_server
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  mime: ^1.0.0
  path: ^1.8.0
dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.0
  test_api: ^0.7.0
