name: belatuk_http_server
version: 2.0.1
description: A collection of useful utility classes for building HTTP server.
homepage: https://github.com/dukefirehawk/belatuk_http_server
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  mime: ^1.0.0
  path: ^1.8.0
dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.0
  test_api: ^0.4.1
